spring.security.user.name=admin
spring.security.user.password=admin123

vaadin.launch-browser=true
spring.application.name=Event_Reservation
server.port=8080

spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driver-class-name=org.h2.Driver
# H2 Database - Authentification
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE