spring.application.name=Event_Reservation
server.port=8089

# Vaadin
vaadin.allowed-packages=com.event.event_reservation
vaadin.launch-browser=true
vaadin.productionMode=false

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# H2 Database (PERSISTANTE)
spring.datasource.url=jdbc:h2:file:./data/eventdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# CONFIGURATION MISE À JOUR AVEC LE NOUVEAU MODÈLE
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}

# On remplace llama3-8b-8192 par le nouveau Llama 3.3 ou 3.1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Rappel : Pas de /v1 à la fin de l'URL pour éviter l'erreur 404 précédente
vaadin.pushMode=automatic