-- ============================================
-- 📄 data.sql - INITIALISATION COMPLÈTE
-- 📁 Chemin: src/main/resources/data.sql
-- ============================================

-- 1. NETTOYAGE DES DONNÉES
DELETE FROM reservations;
DELETE FROM events;
DELETE FROM users;

-- 2. RÉINITIALISATION DES COMPTEURS
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservations ALTER COLUMN id RESTART WITH 1;

-- ========== 1. UTILISATEURS (Total: 7) ==========

-- ADMIN
INSERT INTO users (id, nom, prenom, email, password, role, date_inscription, actif, telephone, theme_preference)
VALUES (1, 'Admin', 'System', 'admin@event.ma', '$2a$10$nh/ydhEx0J9QOw1LL8.Ge.qD0WVhQYT6KqgjWACkvBdJfab5t06p.', 'ADMIN', CURRENT_TIMESTAMP, true, '0600000001', 'LIGHT');

-- ORGANISATEURS
INSERT INTO users (id, nom, prenom, email, password, role, date_inscription, actif, telephone, theme_preference) VALUES
                                                                                                                     (2, 'Alami', 'Youssef', 'organizer1@event.ma', '$2a$10$88s85dmiQq5ehUTSoxBtBefJ1s/8JlqGAHRnAjHSnxhIc.p3Dbtki', 'ORGANIZER', CURRENT_TIMESTAMP, true, '0600000002', 'LIGHT'),
                                                                                                                     (3, 'Bennani', 'Fatima', 'organizer2@event.ma', '$2a$10$88s85dmiQq5ehUTSoxBtBefJ1s/8JlqGAHRnAjHSnxhIc.p3Dbtki', 'ORGANIZER', CURRENT_TIMESTAMP, true, '0600000003', 'LIGHT'),
                                                                                                                     (9, 'Soulaimane', 'Benayad', 'organizer3@event.ma', '$2a$10$88s85dmiQq5ehUTSoxBtBefJ1s/8JlqGAHRnAjHSnxhIc.p3Dbtki', 'ORGANIZER', CURRENT_TIMESTAMP, true, '0600000009', 'LIGHT');

-- CLIENTS
INSERT INTO users (id, nom, prenom, email, password, role, date_inscription, actif, telephone, theme_preference) VALUES
                                                                                                                     (4, 'El Fassi', 'Ahmed', 'client1@event.ma', '$2a$10$.znZqOkRvvehaQvlhUmPFuvOxaDIOW18L2pdD2z6y0vlY3FX1Xcue', 'CLIENT', CURRENT_TIMESTAMP, true, '0600000004', 'LIGHT'),
                                                                                                                     (5, 'Idrissi', 'Nadia', 'client2@event.ma', '$2a$10$.znZqOkRvvehaQvlhUmPFuvOxaDIOW18L2pdD2z6y0vlY3FX1Xcue', 'CLIENT', CURRENT_TIMESTAMP, true, '0600000005', 'LIGHT'),
                                                                                                                     (6, 'Elalaoui', 'Hassan', 'client3@event.ma', '$2a$10$.znZqOkRvvehaQvlhUmPFuvOxaDIOW18L2pdD2z6y0vlY3FX1Xcue', 'CLIENT', CURRENT_TIMESTAMP, true, '0600000006', 'LIGHT');


-- ========== 2. ÉVÉNEMENTS (Total: 20) ==========
-- Organisateur 1 (ID 2)
INSERT INTO events (id, titre, description, categorie, date_debut, date_fin, lieu, ville, latitude, longitude, capacite_max, capacite_restante, prix_unitaire, image_url, organisateur_id, statut, date_creation) VALUES
                                                                                                                                                                                                                      (1, 'Summer Music Festival', 'Grand festival de musique estival avec artistes nationaux.', 'CONCERT', DATEADD('DAY', 15, CURRENT_TIMESTAMP), DATEADD('DAY', 16, CURRENT_TIMESTAMP), 'Plage Ain Diab', 'Casablanca', 33.5731, -7.5898, 500, 480, 250.00, 'images/events/music.jpg', 2, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (2, 'Classic Drama Hamlet', 'Une adaptation moderne de la pièce de Shakespeare.', 'THEATRE', DATEADD('DAY', 10, CURRENT_TIMESTAMP), DATEADD('DAY', 10, CURRENT_TIMESTAMP), 'Théâtre Mohammed V', 'Rabat', 34.0144, -6.8326, 200, 180, 150.00, 'images/events/theatre.jpg', 2, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (3, 'Digital Trends 2025', 'Conférence sur le futur du digital au Maroc.', 'CONFERENCE', DATEADD('DAY', 30, CURRENT_TIMESTAMP), DATEADD('DAY', 30, CURRENT_TIMESTAMP), 'Technopark', 'Casablanca', 33.5731, -7.5898, 150, 150, 300.00, 'images/events/tech.jpg', 2, 'BROUILLON', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (4, 'Tennis Open Tanger', 'Tournoi de tennis amateur inter-villes.', 'SPORT', DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), 'Club Municipal', 'Tanger', 35.7595, -5.8340, 100, 0, 80.00, 'images/events/sport.png', 2, 'TERMINE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (5, 'Art et Culture Fès', 'Exposition de tableaux d artistes locaux.', 'AUTRE', DATEADD('DAY', 20, CURRENT_TIMESTAMP), DATEADD('DAY', 25, CURRENT_TIMESTAMP), 'Palais Medina', 'Fès', 34.0331, -5.0003, 80, 75, 40.00, 'images/events/art.png', 2, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (6, 'Rabat Startup Weekend', 'Accélérateur de projets innovants.', 'CONFERENCE', DATEADD('DAY', 5, CURRENT_TIMESTAMP), DATEADD('DAY', 7, CURRENT_TIMESTAMP), 'Université UM6P', 'Rabat', 34.0144, -6.8326, 60, 58, 100.00, 'images/events/job.png', 2, 'PUBLIE', CURRENT_TIMESTAMP);

-- Organisateur 2 (ID 3)
INSERT INTO events (id, titre, description, categorie, date_debut, date_fin, lieu, ville, latitude, longitude, capacite_max, capacite_restante, prix_unitaire, image_url, organisateur_id, statut, date_creation) VALUES
                                                                                                                                                                                                                      (7, 'Jazz Night Marrakech', 'Soirée intime sous les étoiles au coeur de la palmeraie.', 'CONCERT', DATEADD('DAY', 12, CURRENT_TIMESTAMP), DATEADD('DAY', 12, CURRENT_TIMESTAMP), 'Jardin Majorelle', 'Marrakech', 31.6295, -7.9811, 150, 140, 200.00, 'images/events/jazz.jpg', 3, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (8, 'Marketing Summit', 'Rencontre annuelle des professionnels du marketing.', 'CONFERENCE', DATEADD('DAY', 40, CURRENT_TIMESTAMP), DATEADD('DAY', 40, CURRENT_TIMESTAMP), 'Hôtel Hyatt', 'Casablanca', 33.5731, -7.5898, 200, 200, 450.00, 'images/events/marketing.jpg', 3, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (9, 'Championnat Judo', 'Compétition nationale de judo junior.', 'SPORT', DATEADD('DAY', 4, CURRENT_TIMESTAMP), DATEADD('DAY', 4, CURRENT_TIMESTAMP), 'Salle Couverte', 'Fès', 34.0331, -5.0003, 300, 290, 50.00, 'images/events/karate.jpg', 3, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (10, 'Festival Gastronomique', 'Dégustation des meilleurs plats du terroir.', 'AUTRE', DATEADD('DAY', 50, CURRENT_TIMESTAMP), DATEADD('DAY', 52, CURRENT_TIMESTAMP), 'Place des Nations', 'Tanger', 35.7595, -5.8340, 500, 500, 120.00, 'images/events/food.jpg', 3, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (11, 'Spectacle Humour', 'Représentation comique par la troupe locale.', 'THEATRE', DATEADD('DAY', 18, CURRENT_TIMESTAMP), DATEADD('DAY', 18, CURRENT_TIMESTAMP), 'Centre Culturel', 'Casablanca', 33.5731, -7.5898, 150, 145, 90.00, 'images/events/comedy.jpg', 3, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (12, 'Course Cycliste Ville', 'Course solidaire pour la santé.', 'SPORT', DATEADD('DAY', 35, CURRENT_TIMESTAMP), DATEADD('DAY', 35, CURRENT_TIMESTAMP), 'Forêt Hilton', 'Rabat', 34.0144, -6.8326, 400, 400, 50.00, 'images/events/bike.png', 3, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (13, 'Conférence IA Maroc', 'Impact de l IA sur l économie nationale.', 'CONFERENCE', DATEADD('DAY', 70, CURRENT_TIMESTAMP), DATEADD('DAY', 70, CURRENT_TIMESTAMP), 'UM6P', 'Rabat', 34.0144, -6.8326, 250, 250, 0.00, 'images/events/ai.jpg', 3, 'BROUILLON', CURRENT_TIMESTAMP);

-- Organisateur 3 (ID 9)
INSERT INTO events (id, titre, description, categorie, date_debut, date_fin, lieu, ville, latitude, longitude, capacite_max, capacite_restante, prix_unitaire, image_url, organisateur_id, statut, date_creation) VALUES
                                                                                                                                                                                                                      (14, 'Rock Experience', 'Concert live des groupes émergents du Boultek.', 'CONCERT', DATEADD('DAY', 22, CURRENT_TIMESTAMP), DATEADD('DAY', 22, CURRENT_TIMESTAMP), 'L abattoir', 'Casablanca', 33.5731, -7.5898, 300, 290, 100.00, 'images/events/rock.jpg', 9, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (15, 'Gala Charité Atlas', 'Dîner de bienfaisance pour les enfants du Haut Atlas.', 'AUTRE', DATEADD('DAY', 100, CURRENT_TIMESTAMP), DATEADD('DAY', 100, CURRENT_TIMESTAMP), 'La Mamounia', 'Marrakech', 31.6295, -7.9811, 200, 200, 500.00, 'images/events/gala.jpg', 9, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (16, 'Molière à Fès', 'Représentation du Malade Imaginaire.', 'THEATRE', DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), 'Institut Français', 'Fès', 34.0331, -5.0003, 100, 0, 70.00, 'images/events/moliere.jpeg', 9, 'TERMINE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (17, 'Forum Emploi Tanger', 'Connecter les talents du Nord avec les entreprises.', 'CONFERENCE', DATEADD('DAY', 45, CURRENT_TIMESTAMP), DATEADD('DAY', 46, CURRENT_TIMESTAMP), 'Mövenpick', 'Tanger', 35.7595, -5.8340, 500, 500, 0.00, 'images/events/job.png', 9, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (18, 'Match Gala Foot', 'Match amical entre anciens joueurs pros.', 'SPORT', DATEADD('DAY', 8, CURRENT_TIMESTAMP), DATEADD('DAY', 8, CURRENT_TIMESTAMP), 'Stade Père Jégo', 'Casablanca', 33.5731, -7.5898, 600, 580, 40.00, 'images/events/sport.png', 9, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (19, 'Cours Peinture Nature', 'Session de peinture relaxante dans le jardin.', 'AUTRE', DATEADD('DAY', 12, CURRENT_TIMESTAMP), DATEADD('DAY', 12, CURRENT_TIMESTAMP), 'Marrakech Park', 'Marrakech', 31.6295, -7.9811, 40, 35, 150.00, 'images/events/paint.jpg', 9, 'PUBLIE', CURRENT_TIMESTAMP),
                                                                                                                                                                                                                      (20, 'Atelier Cinéma Kids', 'Initiation au montage pour les 8-12 ans.', 'CONFERENCE', DATEADD('DAY', 15, CURRENT_TIMESTAMP), DATEADD('DAY', 15, CURRENT_TIMESTAMP), 'Espace Coworking', 'Rabat', 34.0144, -6.8326, 20, 20, 100.00, 'images/events/cinema.png', 9, 'ANNULE', CURRENT_TIMESTAMP);


-- ========== 3. RÉSERVATIONS (Total: 30) ==========

INSERT INTO reservations (CODE_RESERVATION, COMMENTAIRE, DATE_RESERVATION, EMAIL_CONFIRMATION_ENVOYE, EMAIL_RAPPEL_ENVOYE, MONTANT_TOTAL, NOMBRE_PLACES, STATUT, EVENEMENT_ID, UTILISATEUR_ID) VALUES
                                                                                                                                                                                                   ('EVT-10001', 'Hâte de venir !', CURRENT_TIMESTAMP, TRUE, FALSE, 500.00, 2, 'CONFIRMEE', 1, 4),
                                                                                                                                                                                                   ('EVT-10002', NULL, DATEADD('DAY', -1, CURRENT_TIMESTAMP), TRUE, FALSE, 150.00, 1, 'CONFIRMEE', 2, 4),
                                                                                                                                                                                                   ('EVT-10003', 'Accès PMR', CURRENT_TIMESTAMP, TRUE, FALSE, 400.00, 2, 'CONFIRMEE', 7, 4),
                                                                                                                                                                                                   ('EVT-10004', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 250.00, 1, 'CONFIRMEE', 1, 5),
                                                                                                                                                                                                   ('EVT-10005', 'Pour mes enfants', CURRENT_TIMESTAMP, TRUE, FALSE, 300.00, 6, 'CONFIRMEE', 9, 5),
                                                                                                                                                                                                   ('EVT-10006', 'Désolé je ne peux plus', DATEADD('DAY', -2, CURRENT_TIMESTAMP), FALSE, FALSE, 150.00, 1, 'ANNULEE', 19, 5),
                                                                                                                                                                                                   ('EVT-10007', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 600.00, 4, 'CONFIRMEE', 2, 6),
                                                                                                                                                                                                   ('EVT-10008', 'Super festival', CURRENT_TIMESTAMP, TRUE, FALSE, 400.00, 2, 'CONFIRMEE', 7, 6),
                                                                                                                                                                                                   ('EVT-10009', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 200.00, 2, 'CONFIRMEE', 14, 6),
                                                                                                                                                                                                   ('EVT-10010', 'Paiement en attente', CURRENT_TIMESTAMP, FALSE, FALSE, 450.00, 1, 'EN_ATTENTE', 8, 4),
                                                                                                                                                                                                   ('EVT-10011', NULL, DATEADD('DAY', -1, CURRENT_TIMESTAMP), TRUE, FALSE, 200.00, 1, 'CONFIRMEE', 14, 4),
                                                                                                                                                                                                   ('EVT-10012', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 180.00, 2, 'CONFIRMEE', 11, 4),
                                                                                                                                                                                                   ('EVT-10013', 'Virement en cours', CURRENT_TIMESTAMP, FALSE, FALSE, 100.00, 1, 'EN_ATTENTE', 6, 5),
                                                                                                                                                                                                   ('EVT-10014', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 300.00, 2, 'CONFIRMEE', 19, 5),
                                                                                                                                                                                                   ('EVT-10015', 'En famille', CURRENT_TIMESTAMP, TRUE, FALSE, 360.00, 4, 'CONFIRMEE', 11, 6),
                                                                                                                                                                                                   ('EVT-10016', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 750.00, 3, 'CONFIRMEE', 1, 4),
                                                                                                                                                                                                   ('EVT-10017', 'Dernière minute', DATEADD('HOUR', -5, CURRENT_TIMESTAMP), TRUE, FALSE, 80.00, 2, 'CONFIRMEE', 18, 4),
                                                                                                                                                                                                   ('EVT-10018', NULL, CURRENT_TIMESTAMP, FALSE, FALSE, 500.00, 1, 'ANNULEE', 15, 4),
                                                                                                                                                                                                   ('EVT-10019', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 200.00, 1, 'CONFIRMEE', 7, 5),
                                                                                                                                                                                                   ('EVT-10020', 'Confirmation rapide svp', CURRENT_TIMESTAMP, TRUE, FALSE, 400.00, 2, 'CONFIRMEE', 7, 6),
                                                                                                                                                                                                   ('EVT-10021', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 300.00, 2, 'CONFIRMEE', 2, 5),
                                                                                                                                                                                                   ('EVT-10022', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 100.00, 2, 'CONFIRMEE', 9, 6),
                                                                                                                                                                                                   ('EVT-10023', 'Proche de la scène', CURRENT_TIMESTAMP, TRUE, FALSE, 150.00, 1, 'CONFIRMEE', 2, 4),
                                                                                                                                                                                                   ('EVT-10024', NULL, DATEADD('DAY', -1, CURRENT_TIMESTAMP), TRUE, FALSE, 200.00, 4, 'CONFIRMEE', 5, 5),
                                                                                                                                                                                                   ('EVT-10025', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 200.00, 5, 'CONFIRMEE', 18, 6),
                                                                                                                                                                                                   ('EVT-10026', 'Test résa', CURRENT_TIMESTAMP, TRUE, FALSE, 120.00, 3, 'CONFIRMEE', 5, 4),
                                                                                                                                                                                                   ('EVT-10027', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 250.00, 1, 'CONFIRMEE', 1, 5),
                                                                                                                                                                                                   ('EVT-10028', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 450.00, 1, 'CONFIRMEE', 8, 6),
                                                                                                                                                                                                   ('EVT-10029', 'En attente virement', CURRENT_TIMESTAMP, FALSE, FALSE, 100.00, 1, 'EN_ATTENTE', 6, 4),
                                                                                                                                                                                                   ('EVT-10030', NULL, CURRENT_TIMESTAMP, TRUE, FALSE, 90.00, 1, 'CONFIRMEE', 11, 5);